### PR TITLE
Added meta-package

### PR DESCRIPTION
**Pull request by LanderU**
Signed-off-by: LanderU <lander.usategui@gmail.com>

### CODE REVIEW

**Review by carlossvg — COMMENTED** [review]
Is it possible to just use `pendulum` for the meta-package name?

**Comment by LanderU** [comment]
@carlossvg let me check if this collide with other packages.

**Comment by LanderU** [comment]
@carlossvg done, also I've squashed the commits.

**Comment by LanderU** [comment]
Btw, tested locally on a ros2 workspace with: https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos

**Review by carlossvg — APPROVED** [review]
Great, LGTM!

**Pull request merged**
