### PR TITLE
Update ade installation command

### PR DESCRIPTION
**Pull request by carlossvg**

### CODE REVIEW

**Comment by carlossvg** [comment]
@LanderU If aarch64 is not supported I think we should add a note saying x86 only.

**Comment by LanderU** [comment]
@carlossvg 

> @LanderU If aarch64 is not supported I think we should add a note saying x86 only.

Yes, we need to add it. Should we do it on a separate PR?

**Review by LanderU — APPROVED** [review]
LGTM!

**Comment by carlossvg** [comment]
> @carlossvg
> 
> > @LanderU If aarch64 is not supported I think we should add a note saying x86 only.
> 
> Yes, we need to add it. Should we do it on a separate PR?

Ok!

**Pull request merged**
