### PR TITLE
Add user to tracing group on ADE

### PR DESCRIPTION
**Pull request by LanderU**
Signed-off-by: LanderU <lander.usategui@gmail.com>

### CODE REVIEW

**Review by igorrecioh — APPROVED** [review]

**Review by carlossvg — COMMENTED** [review]
Could you explain how to test the effect of this change?

**Comment by LanderU** [comment]
> There is a post-installation procedure that must be done in order to allow non-root users to (transparently) start LTTng daemon for monitoring kernel events. These users must be added in the tracing group as shown below (in Fedora 17):
> # Create group if it doesn't exist
> $ sudo groupadd -r tracing
> # Add <username> to the group
> $ sudo usermod -aG tracing <username>

From: https://www.ibm.com/support/pages/howto-tracing-lttng

**Comment by carlossvg** [comment]
@LanderU Sorry, I was not specific enough. I meant how can I validate the effect on the ADE image and the demo after the change, i.e: use and lttng command, launch kernel tracing, etc.

**Comment by LanderU** [comment]
@carlossvg aagh sorry, let me create a guideline.

**Comment by carlossvg** [comment]
@LanderU LGTM

**Pull request merged**
