### PR TITLE
Replace foxy with rolling

### PR DESCRIPTION
**Pull request by carlossvg**
@LanderU This PR updates Foxy references to Rolling. I updated some names in the docker and ADE files but this would need to update the docker images too. Instead, I think this is a good opportunity to use the https://gitlab.apex.ai/apex.ai-public/ros2-ade.

### CODE REVIEW

**Review by LanderU — APPROVED** [review]
LGTM!

**Comment by LanderU** [comment]
@carlossvg, I'll start deprecating our ade version and use ros2-ade, do you agree?

**Comment by carlossvg** [comment]
> @carlossvg, I'll start deprecating our ade version and use ros2-ade, do you agree?

Okay, do you want to do that in this PR or in a separate one? If it's in a separate one I will remove the ADE/docker changes from this PR.

**Comment by LanderU** [comment]
@carlossvg, let's merge this one and I'll open a new issue to cover the deprecation part.

**Pull request merged**
