### PR TITLE
Add pendulum_controller and pendulum_driver unit tests

### PR DESCRIPTION
**Pull request by carlossvg**

### CODE REVIEW

**Comment by carlossvg** [comment]
@LanderU Could you enable coverage measurement and add a badge in the README?

**Review by LanderU — CHANGES_REQUESTED** [review]
@carlossvg, could you please fix merge conflicts?

**Comment by carlossvg** [comment]
@LanderU done

**Review by LanderU — APPROVED** [review]
LGTM!

**Pull request merged**
